version: '3.7'

networks:
  backend_network:
    driver: overlay
    
services:
  node:
    image: akshaal/akua:$AKUA_VERSION
    restart: always
    networks:
      - backend_network
    volumes:
      - /dev/ttyAMA0:/dev/ttyS0
    deploy:
      replicas: 1
      update_config:
        order: start-first
    ports:
      - 3000:3000