#!/bin/sh

# Fuse 0 means set, fuse 1 means unset!
#
# Low 0xFF all bits are unset:
#   CKDIV8  - unset, ours CLK is not divided by 8
#   CKOUT   - unset, we don't output CLK on pin
#   SUT1    - unset, we use maximum startup delay
#   SUT0    - unset, we use maximum startup delay
#   CKSEL3  - unset, we use > 8 MHZ External oscillator
#   CKSEL2  - unset, we use > 8 MHZ External oscillator
#   CKSEL1  - unset, we use > 8 MHZ External oscillator
#   CKSEL0  - unset, we use > 8 MHZ External oscillator
#
# High 0xDB all bits are unset:
#   OCDEN    - unset, we don't use onchip debug
#   JTAGEN   - unset, we don't use JTAG
#   SPIEN    - set, we use serial programming interface to download firmware
#   WDTON    - unset, we don't enable watchdog using fuses (we enable it in code)
#   EESAVE   - unset, we don't preserve EEPROM on chip-erase
#   BOOTSZ1  - whatever, we don't care, because BOOTRST is not set
#   BOOTSZ0  - whatever, we don't care, because BOOTRST is not set
#   BOOTRST  - unset, we don't use bootloader (if unset then program starts at address 0x000...,
#              otherwise it would start using address configured by BOOTSZ)

avrdude -c usbasp -p m2560 -B 2400 -U lfuse:w:0xFF:m -U hfuse:w:0xDF:m
