#!/bin/sh

# Use to run akua in dev environment

export AKUA_VERSION=$(git describe --tags --always)

cd `dirname "$0"`

mkdir -p temp/db-unknown

cd src/jsclient

echo "Use environment variable AKUA_PORT to override AVR USB port in dev environment."
echo "Use environment variable AKUA_NEXTION_PORT to override NEXTION USB port in dev environment."

npm run dev
