#!/bin/sh

export AKUA_VERSION=$(git describe --tags --always)

P_UID=$(id --user)
P_GID=$(id --group)

export P_UID
export P_GID

./build-docker && echo "\n-----------------------------------------------------------" && docker-compose -f docker-compose.production.yml -f docker-compose.dev-config.yml up "$@"
